//this code for only time and date zone setting in javascript
var date = new Date()
console.log(date.toDateString())
console.log(date.toTimeString())
console.log(date.toLocalString())
console.log(date.getFullYear())
console.log(date.getDate())
console.log(date.getMonth())
console.log(date.getHours())
console.log(date.getMinutes())
console.log(date.getSeconds())
console.log(date.getUTCMilliseconds())